#! /bin/sh
### BEGIN INIT INFO
# Provides:		cybercached
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	CyberCache cluster - session/FPC store for web applications
# Description:		CyberCache cluster - session/FPC store for Magento and other Zend framework-based web applications
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/cybercached
DAEMON_ARGS=/etc/cybercache/cybercached.cfg
NAME=cybercached
DESC=CyberCache

RUNDIR=/var/run/cybercache
PIDFILE=$RUNDIR/cybercached.pid

test -x $DAEMON || exit 0

if [ -r /etc/default/$NAME ]
then
	. /etc/default/$NAME
fi

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	mkdir -p $RUNDIR
	touch $PIDFILE
	chown cybercache:cybercache $RUNDIR $PIDFILE
	chmod 755 $RUNDIR

	if [ -n "$C3_MAX_NUM_HANDLES" ]
	then
		ulimit -n $C3_MAX_NUM_HANDLES
	fi

  # `--background` is to be removed once `cybercached` starts fork()-ing on its own
  # replace `--quiet` with `--verbose` in test mode
  # v. 1.3.4 change: `umask` set to `003` to make logs etc. readable by everyone
	if start-stop-daemon --quiet --start --umask 003 --background --pidfile $PIDFILE --chuid cybercache:cybercache --exec $DAEMON -- $DAEMON_ARGS
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	;;

  stop)
	echo -n "Stopping $DESC: "
  # replace `--quiet` with `--verbose` in test mode
	if start-stop-daemon --quiet --stop --retry forever/TERM/1 --oknodo --pidfile $PIDFILE --exec $DAEMON
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	rm -f $PIDFILE
	sleep 1
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;

  status)
	echo -n "$DESC is "
  # replace `--quiet` with `--verbose` in test mode
	if start-stop-daemon --quiet --stop --signal 0 --name ${NAME} --pidfile ${PIDFILE}
	then
		echo "running"
	else
		echo "not running"
		exit 1
	fi
	;;

  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
