#! /bin/sh
#
# This file is a part of the implementation of the CyberCache Cluster.
# Written by Vadim Sytnikov.
# Copyright (C) 2016-2019 CyberHULL. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

if [ ! -d /var/run/cybercache ]; then
  echo "ERROR: CyberCache server is not installed properly."
  exit 1
fi

if [ -n "$1" ]; then
  case "$1" in
    --help)
      echo "Use: start-cybercache-server [ --help | --force ]"
      echo "\nIf '--force' option is given, the script will remove cybercached PID before starting the server."
      exit 1
      ;;
    --force)
      shift
      REMOVE_CYBERCACHE_PID=1
      ;;
  esac
fi

if [ $(id -u) -ne 0 ]; then
  echo "This command must be run with 'root' privileges"
  exit 1
fi

rm -f logs/*.log
rm -f logs/*.blf
echo "Cleaned [bin]log files."
if [ -n "$REMOVE_CYBERCACHE_PID" ]; then
  rm -f /var/run/cybercache/cybercached.pid
  echo "Removed PID file."
fi

cybercached "$@" config/cybercached-test.cfg
