#! /bin/sh
#
# This file is a part of the implementation of the CyberCache Cluster.
# Written by Vadim Sytnikov.
# Copyright (C) 2016-2019 CyberHULL. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

set -e

# remove config file links so that PHP does not try to load the extension
if [ "$1" = "remove" ]; then
  for php_mode in "cli" "cgi" "fpm" "apache2"; do
    for php_ver in "7.0" "7.1" "7.2" "7.3"; do
      ini_link="/etc/php/$php_ver/$php_mode/conf.d/20-cybercache.ini"
      if [ -L "$ini_link" ]; then
        rm "$ini_link"
      fi
    done
  done
  # remove server link
  if [ -L "/usr/bin/cybercached" ]; then
    rm "/usr/bin/cybercached"
  fi
fi

if [ "$1" = "purge" ]; then
  # remove logs and other data files
	rm -rf /var/lib/cybercache
	rm -rf /var/log/cybercache
	rm -rf /opt/cybercache/tests/logs
  # remove links in the `/etc/rc<runlevel>.d` directories
  update-rc.d cybercached remove >/dev/null
  # remove user (this will also remove the group)
	userdel cybercache
fi
