#! /bin/sh
#
# This file is a part of the implementation of the CyberCache Cluster.
# Written by Vadim Sytnikov.
# Copyright (C) 2016-2019 CyberHULL. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

set -eu

USER="cybercache"
GROUP="$USER"

# `init.d/cybercached` will take care of `/var/run/cybercache`
chown -R $USER:$GROUP /var/lib/cybercache
chown -R $USER:$GROUP /var/log/cybercache

# make extension available to PHP subsystems
for php_mode in "cli" "cgi" "fpm" "apache2"; do
  for php_ver in "7.0" "7.1" "7.2" "7.3"; do
    if [ -d "/etc/php/$php_ver/$php_mode/conf.d" ]; then
      ln -sf /etc/php/$php_ver/mods-available/cybercache.ini /etc/php/$php_ver/$php_mode/conf.d/20-cybercache.ini
    fi
  done
done

# generate API stubs
C3_STUB_DIR=/opt/cybercache/stub
C3_STUB_PHP_DIR=$C3_STUB_DIR/stubs/cybercache
API_INFO_FILE=$(tempfile)
API_INFO_SCRIPT=$C3_STUB_DIR/generate_api_info
API_STUB_SCRIPT=$C3_STUB_DIR/generate_api_stub
$API_INFO_SCRIPT $API_INFO_FILE
if [ $? -ne 0 ]; then
  echo "ERROR: could not generate API info file '$API_INFO_FILE'"
  exit 1
fi
API_STUB_FILE=$C3_STUB_PHP_DIR/cybercache.php
$API_STUB_SCRIPT $API_INFO_FILE $API_STUB_FILE
if [ $? -ne 0 ]; then
  echo "ERROR: could not generate API stub file '$API_STUB_FILE'"
  exit 1
fi

# create symlink to default (for the edition) server version
if [ -x "/usr/bin/cybercached-ee" ]; then
  ln -sf /usr/bin/cybercached-ee /usr/bin/cybercached
else
  if [ -x "/usr/bin/cybercached-ce" ]; then
    ln -sf /usr/bin/cybercached-ce /usr/bin/cybercached
  else
    exit 1
  fi  
fi

# start CyberCache server
if [ -x "/etc/init.d/cybercached" ]; then
  update-rc.d cybercached defaults > /dev/null
  invoke-rc.d cybercached start || exit $?
fi

is_running() {
  ps cax | grep "$1" > /dev/null
}

# optionally restart Apache2 server
if [ -x "/etc/init.d/apache2" ]; then
  if is_running apache2; then
    invoke-rc.d apache2 restart || exit $?
  fi
fi

# optionally restart php-fpm service
for php_ver in "7.0" "7.1" "7.2" "7.3"; do
  fpm_service=php${php_ver}-fpm
  if [ -s "/var/run/php/${fpm_service}.pid" ]; then
    invoke-rc.d ${fpm_service} restart || exit $?
  fi
done
