#! /bin/bash
#
# This file is a part of the implementation of the CyberCache Cluster.
# Written by Vadim Sytnikov.
# Copyright (C) 2016-2019 CyberHULL. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# check that PhantomJS is installed
PJS=$(which phantomjs)
if [[ -z "$PJS" ]]; then
  echo "CyberCache Warmer requires PhantomJS to run."
  echo "Please install it (`sudo apt install phantomjs` on Ubuntu-based distributions) and try again."
  exit 1
fi

COOKIES=/tmp/cybercache-warmer-cookies.txt
$PJS --cookies-file="$COOKIES" /opt/cybercache/warmer/warmer.js "$@"
