#! /bin/sh
#
# This file is a part of the implementation of the CyberCache Cluster.
# Written by Vadim Sytnikov.
# Copyright (C) 2016-2019 CyberHULL. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# if generation fails, we shouldn't be left with previous version
rm -f c3version.js

# get new version number from `scripts/c3p.cfg`
../../scripts/c3p -f c3version.js.c3p -o c3version.js
