#! /bin/sh
#
# This file is a part of the implementation of the CyberCache Cluster.
# Written by Vadim Sytnikov.
# Copyright (C) 2016-2019 CyberHULL. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

PP='../scripts/c3p'
UTIL='../scripts/c3mcp'

SFILE='cybercached.mdcfg'
CFILE_CE='ce/cybercached.cfg'
MFILE_CE='ce/cybercached.md'
CFILE_EE='ee/cybercached.cfg'
MFILE_EE='ee/cybercached.md'

mkdir -p ce ee
rm -f "$CFILE_CE" "$MFILE_CE" "$CFILE_EE" "$MFILE_EE"

$PP -f "$SFILE" -e community | $UTIL -c -o "$CFILE_CE"
$PP -f "$SFILE" -e community | $UTIL -m -o "$MFILE_CE"
$PP -f "$SFILE" -e enterprise | $UTIL -c -o "$CFILE_EE"
$PP -f "$SFILE" -e enterprise | $UTIL -m -o "$MFILE_EE"
