#! /bin/sh
#
# This file is a part of the implementation of the CyberCache Cluster.
# Written by Vadim Sytnikov.
# Copyright (C) 2016-2019 CyberHULL. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

if [ $(id -u) -ne 0 ]; then
  echo "This command must be run with 'root' privileges"
  exit 1
fi

switch_to() {
  LNAME="/usr/bin/cybercached"
  FNAME="${LNAME}-$1"
  if ! [ -x "$FNAME" ]; then
    echo "ERROR: executable '$FNAME' does not exist"
    exit 1
  fi
  if [ -s "/var/run/cybercache/cybercached.pid" ]; then
    /etc/init.d/cybercached stop
    if [ $? -ne 0 ]; then
      echo "ERROR: could not stop 'cybercached' daemon"
      exit 1
    fi
    STOPPED_CYBERCACHED=1
  fi
  ln -sf "$FNAME" "$LNAME"
  if [ $? -ne 0 ]; then
    echo "ERROR: could not link '$LNAME' to '$FNAME'"
    exit 1
  fi
  echo "Switching succeeded: current server is $FNAME"
  if [ $STOPPED_CYBERCACHED ]; then
    /etc/init.d/cybercached start
    if [ $? -ne 0 ]; then
      echo "ERROR: could not restart 'cybercached' daemon"
      exit 1
    fi
    echo "Server successfully restarted."
  fi
}

case "$1" in
  production)
    switch_to "ee"
    ;;
  instrumented)
    switch_to "iee"
    ;;
  *)
    echo "Use: switch-server-version {production|instrumented}"
    exit 1
    ;;
esac
