#! /bin/bash
#
# This file is a part of the implementation of the CyberCache Cluster.
# Written by Vadim Sytnikov.
# Copyright (C) 2016-2019 CyberHULL. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

md_file="$1"
man_file="$2"
man_section="$3"
ts=date:$(date "+%B %d, %Y")
subtitle=header:"$4"

# check if pandoc supports the -S switch
if echo x | pandoc -S &>/dev/null; then
  from_markdown='-f markdown -S'
else
  from_markdown='-f markdown+smart'
fi

pandoc --wrap=none -s $from_markdown -t man \
  -V author:"Vadim Sytnikov" -V "$ts" -V "$subtitle" -V hyphenate:false \
  -V title:"cybercache" -V section:$man_section -V adjusting:l \
  -V footer:"Copyright (C) 2019 CyberHULL" \
  -o "$man_file" "$md_file"
if [ $? -ne 0 ]; then
  echo "ERROR: could not convert '$md_file' to '$man_file'"
  exit 1
fi
