#! /bin/bash
#
# This file is a part of the implementation of the CyberCache Cluster.
# Written by Vadim Sytnikov.
# Copyright (C) 2016-2019 CyberHULL. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

C3_VERSION=$(echo 'C3P[VERSION]' | ../scripts/c3p)
C3_ITERATION=1
C3_CE_DEB="cybercache-ce_${C3_VERSION}-${C3_ITERATION}_amd64.deb"
C3_CE_RPM="cybercache-ce-${C3_VERSION}-${C3_ITERATION}.x86_64.rpm"
C3_EE_DEB="cybercache-ee_${C3_VERSION}-${C3_ITERATION}_amd64.deb"
C3_EE_RPM="cybercache-ee-${C3_VERSION}-${C3_ITERATION}.x86_64.rpm"
C3_LOG="create_all_packages.log"

# remove existing packages, if any
echo "Removing old packages..."
rm -f "$C3_CE_DEB" "$C3_EE_DEB" "$C3_CE_RPM" "$C3_EE_RPM" "$C3_LOG"

# generate server .md and .cfg files for both editions
echo "Generating server documentation and configuration files..."
PDIR=$(pwd)
cd ../config
./generate_md_cfg
cd "$PDIR"

# download the Magento 2 extension
./get_magento2_extension m2_ext_tmp

# create and verify Community Edition DEB and RPM packages
echo "Creating Community Edition package '$C3_CE_DEB'..."
./create_package 'community' 'deb' $C3_VERSION $C3_ITERATION > "$C3_LOG"
if [ $? -ne 0 ]; then
  echo "ERROR: could not create 'community' edition package"
  exit 1
fi
echo "Verifying Community Edition DEB package..."
./verify_deb_package "$C3_CE_DEB"
echo "Creating Community Edition RPM package..."
fpm -s deb -t rpm "$C3_CE_DEB"

# create and verify Enterprise Edition DEB and RPN packages
echo "Creating Enterprise Edition DEB package '$C3_EE_DEB'..."
./create_package 'enterprise' 'deb' $C3_VERSION $C3_ITERATION >> "$C3_LOG"
if [ $? -ne 0 ]; then
  echo "ERROR: could not create 'enterprise' edition package"
  exit 1
fi
echo "Verifying Enterprise Edition DEB package..."
./verify_deb_package "$C3_EE_DEB"
echo "Creating Enterprise Edition RPM package..."
fpm -s deb -t rpm "$C3_EE_DEB"
