#! /bin/bash
#
# This file is a part of the implementation of the CyberCache Cluster.
# Written by Vadim Sytnikov.
# Copyright (C) 2016-2019 CyberHULL. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# -----------------------------------------------------------------------------
#
# Creates a Debian package suitable for distribution.
#
# In a nutshell, this script downloads the Magento 2 extension sources
# to the appropriate location, then calls debuild to build the source package.

SCRIPTDIR=$(cd "$(dirname "$0")" && pwd)

set -e

"$SCRIPTDIR"/get_magento2_extension "$SCRIPTDIR"/../src/magento2
(cd "$SCRIPTDIR"/.. && debuild -S -sa)
