#! /bin/bash
#
# This file is a part of the implementation of the CyberCache Cluster.
# Written by Vadim Sytnikov.
# Copyright (C) 2016-2019 CyberHULL. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

REPO=https://github.com/cyberhull/magento2-module-cybercache

EXT_TMP=$1
if [[ -z $EXT_TMP ]]; then
    echo "$(basename "$0") TMPDIR"
    echo "Download a compatible version of the Magento 2 extension into TMPDIR"
    exit 1
fi
if [[ -a $EXT_TMP && ! -d $EXT_TMP ]]; then
    echo "ERROR: $EXT_TMP exists and is not a directory. Refusing to overwrite"
    exit 1
fi

# source product version from scripts/c3p.cfg
VERSION=$(echo C3P[VERSION] | ../scripts/c3p)
VERSION_RE=${VERSION//./\\.}
VERSION_RE=^${VERSION_RE%.*}..*

# determine the latest tag matching the VERSION pattern
LATEST=$(git ls-remote $REPO.git | sed -e '/\/tags\//!d' -e 's/.*\/tags\///' | grep "$VERSION_RE" | sort -Vr | head -n1)

# download the extension
[[ -d $EXT_TMP ]] && rm -r "$EXT_TMP"
mkdir -p "$EXT_TMP"
echo "Downloading Magento 2 extension $LATEST"
curl -L $REPO/archive/$LATEST.tar.gz | tar -C "$EXT_TMP" -xz --strip-components=1
