#! /bin/bash
#
# This file is a part of the implementation of the CyberCache Cluster.
# Written by Vadim Sytnikov.
# Copyright (C) 2016-2019 CyberHULL. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

if [ -n "$1" ]; then
  # detect old Lintian versions
  ACTUAL=$(lintian --version | sed -E 's/.*?v([0-9.]+).*/\1/')
  GOOD=2.5.50
  # use sort to order version numbers
  MIN=$( (echo $ACTUAL; echo $GOOD) | sort -V | head -n1)
  if [[ $MIN == $GOOD ]]; then
      SUPPRESS=lintian-suppressed-tags.lst
  else
      SUPPRESS=lintian-suppressed-tags-pre-2.5.50.lst
  fi

  lintian --check --suppress-tags-from-file $SUPPRESS "$1"
  if [ $? -eq 0 ]; then
    echo "Verification complete: no [unsuppressed] errors.";
  else
    echo "There were errors during verification."
  fi
else
  echo "Use: verify_deb_package.sh <deb-file-name>";
fi
